- src/runner.nim
This improves the readability of (especially) the `run all` suite's output, and also improves readability with the upcoming tests.
> Refactor(runner): Reduce verbosity

- src/unittest_json.nim
This PR changes the JSON generated by `unittest_json.nim` to conform slightly better with [the spec](https://github.com/exercism/automated-tests/blob/master/docs/interface.md).
Consider an example: a single-test test file that fails. This PR causes the following `diff`:
```diff
{
+  "status": "fail",
"tests": [
{
"name": "two() returns 2",
-      "output": "",
"status": "fail",
-      "message": "/some/path/some_file.nim(8, 18): Check failed: two() == 2\\ntwo() was 0"
+      "message": "/some/path/some_file.nim(8, 18): Check failed: two() == 2\\ntwo() was 0",
+      "output": ""
}
-  ],
+  ]
-  "status": "fail"
}
```
See the commit message for more details.
> Fix(unittest_json): Change order of JSON keys

- src/runner.nim
- tests/trunner.nim
- tests/trunner_repo_solutions.nim
We made a processed exercise test file able to import `unittest_json` simply by copying `unittest_json.nim` to the temporary directory. However, we did this copying only when running the existing tests, and not when executing the `runner` binary.
Therefore this commit moves the copying of `unittest_json.nim` into `runner.nim`.
I have an upcoming PR that adds tests for the `runner` binary.
> Fix(runner): Fix importing of `unittest_json`

- tests/trunner.nim
Let's use this convention:
- The runner outputs `results.json` with zero newlines.
- The `expected_results.json` is in `pretty` format (which is more readable for maintainers), and has a final newline.
`tests/trunner.nim` has the ability to write `expected_results.json`, which is useful during development when adding new test cases. This PR makes that written file comply with the second rule above.
> Refactor(trunner): Add final newline in `writeJson`

- tests/fail/multiple_tests_all_fail/expected_results.json
- tests/fail/multiple_tests_all_fail/identity.nim
- tests/fail/multiple_tests_all_fail/identity_test.nim
- tests/fail/multiple_tests_multiple_fails/expected_results.json
- tests/fail/multiple_tests_multiple_fails/identity.nim
- tests/fail/multiple_tests_multiple_fails/identity_test.nim
- tests/fail/multiple_tests_one_fail_first/expected_results.json
- tests/fail/multiple_tests_one_fail_first/identity.nim
- tests/fail/multiple_tests_one_fail_first/identity_test.nim
- tests/fail/multiple_tests_one_fail_last/expected_results.json
- tests/fail/multiple_tests_one_fail_last/identity.nim
- tests/fail/multiple_tests_one_fail_last/identity_test.nim
- tests/fail/multiple_tests_one_fail_middle/expected_results.json
- tests/fail/multiple_tests_one_fail_middle/identity.nim
- tests/fail/multiple_tests_one_fail_middle/identity_test.nim
- tests/fail/single_test/expected_results.json
- tests/fail/single_test/identity.nim
- tests/fail/single_test/identity_test.nim
- tests/pass/multiple_tests/expected_results.json
- tests/pass/multiple_tests/identity.nim
- tests/pass/multiple_tests/identity_test.nim
This PR adds simple `pass` and `fail` cases where the `runner` works. It also documents the current flawed behavior with the content of `message` keys so that it's easier to improve in the future.
See the commit messages for more details.
> Test: Add simple `pass` and `fail` test cases

- .github/workflows/ci.yml
- Dockerfile
This PR updates our `Dockerfile` and CI workflow to use the latest stable Nim release.
See: https://nim-lang.org/blog/2020/06/17/version-122-released.html
> Chore: Bump nim from 1.2.0 to 1.2.2

- src/unittest_json.nim
- tests/error/runtime_exception_in_solution/expected_results.json
- tests/error/runtime_exception_in_solution/identity.nim
- tests/error/runtime_exception_in_solution/identity_test.nim
If the test file and the user's solution both compile successfully, a runtime problem like an uncaught exception should produce:
- a top-level `status` of `fail`.
- a test-level `status` of `error`.
However, in such cases our test-level `status` was `fail`. This PR changes it to `error`, and adds a test.
I think we can make the specification clearer on this point.
@iHiD quote from Slack:
> If the solution fails to compile or the tests can’t run for some reason, then the top level status should be `error`. If the tests can run, then the top level status should be `pass` or `fail`. So if a test runs but `error`s, that should result in the top level status being `fail`.
> To put it another way, in the UI, if we get a top level `error`, we’ll only show the top level message, not any of the …
> Fix(unittest_json): Support test-level `error` status

- src/runner.nim
- tests/error/compiletime_crash_in_solution/expected_results.json
- tests/error/compiletime_crash_in_solution/identity.nim
- tests/error/compiletime_crash_in_solution/identity_test.nim
- tests/error/compiletime_error_empty_solution/expected_results.json
- tests/error/compiletime_error_empty_solution/identity_test.nim
- tests/error/compiletime_error_type_mismatch_in_test/expected_results.json
- tests/error/compiletime_error_type_mismatch_in_test/identity.nim
- tests/error/compiletime_error_type_mismatch_in_test/identity_test.nim
- tests/error/compiletime_error_undeclared_variable_in_solution/expected_results.json
- tests/error/compiletime_error_undeclared_variable_in_solution/identity.nim
- tests/error/compiletime_error_undeclared_variable_in_solution/identity_test.nim
- tests/error/compiletime_exception_in_solution/expected_results.json
- tests/error/compiletime_exception_in_solution/identity.nim
- tests/error/compiletime_exception_in_solution/identity_test.nim
- tests/trunner.nim
- tests/trunner_repo_solutions.nim
This PR:
- Improves the clarity of the path handling code in `runner.nim`.
- Fixes the runner so that a compile error produces `results.json` with a top-level `error` status. 
- Adds test cases for top-level `error` status.
See the commit messags for more details.
> Fix: Support top-level `error` status (and add tests)

- .github/workflows/ci.yml
- Dockerfile
This PR updates our `Dockerfile` and CI workflow to use the latest stable Nim release.
Changelog: https://github.com/nim-lang/Nim/compare/v1.2.2...v1.2.4
It's a short changelog. But it includes a small commit from me... so it must be important :)
Requesting a review from @exercism/ops as this PR changes the `Dockerfile`.
> Chore: Bump nim from 1.2.2 to 1.2.4

- src/runner.nim
- tests/error/compiletime_error_closing_quote_expected/expected_results.json
- tests/error/compiletime_error_closing_quote_expected/hello_world.nim
- tests/error/compiletime_error_closing_quote_expected/hello_world_test.nim
The `results.json` files with compilation errors were being written directly without using the `json` package, and therefore if the string had double-quotes in the messages, it wouldn't be able to be parsed. 
This is demonstrated [here](https://github.com/exercism/nim-test-runner/runs/867853937) by having a test case where the compilation error message has a double-quote in the message and the parser fails.
The aforementioned submission file is 
```nim
func hello*: string =
"Hello, World!
```
and the test file is
```nim
import unittest
import hello_world
suite "Hello World":
test "say hi":
check hello() == "Hello, World!"
```
> Fix(runner): escape compilation quotes in messages 

- .github/workflows/ci.yml
- tests/error/compiletime_error_closing_quote_expected/hello_world_test.nim
- tests/pass/single_test/expected_hello_world_test_prepared.nim
- tests/pass/single_test/expected_results.json
- tests/pass/single_test/hello_world_test.nim
The `ci.yml` workflow always fails during the `diff` at the end of:
https://github.com/exercism/nim-test-runner/blob/0870db148b679665697099de5c01ad42e632839b/.github/workflows/ci.yml#L52-L56
because the `hello-world` test name is different from that expected.
The reason: the `exercism/nim` repo changed that test name from `say hi` to `say hi!` to be consistent with the canonical data.
This PR makes the same change.
See: https://github.com/exercism/nim/commit/06e17d1bad64
> CI: Fix smoke test

- .github/workflows/ci.yml
- Dockerfile
- tests/error/compiletime_crash_in_solution/expected_results.json
- tests/error/compiletime_error_type_mismatch_in_test/expected_results.json
- tests/error/runtime_exception_in_solution/expected_results.json
This PR updates our `Dockerfile` and CI workflow to use the latest stable Nim release.
We skipped Nim 1.2.6.
See:
- https://nim-lang.org/blog/2020/07/30/versions-126-and-108-released.html
- https://nim-lang.org/blog/2020/10/16/version-140-released.html
> Chore: Bump nim from 1.2.4 to 1.4.0

- .github/CODEOWNERS
- .gitignore
The tooling is essential to the functioning of v3. To help ensure that any changes work well with the v3 website, the exercism/maintainers-admin team is added as a codeowner.
See https://github.com/exercism/exercism/issues/5400
> Add exercism/maintainers-admin team as codeowner

- .github/workflows/ci.yml
- src/runner.nim
- tests/error/compiletime_error_empty_solution/expected_results.json
- tests/error/compiletime_error_type_mismatch_in_test/expected_results.json
- tests/error/runtime_exception_in_solution/expected_results.json
- tests/fail/multiple_tests_all_fail/expected_results.json
- tests/fail/multiple_tests_multiple_fails/expected_results.json
- tests/fail/multiple_tests_one_fail_first/expected_results.json
- tests/fail/multiple_tests_one_fail_last/expected_results.json
- tests/fail/multiple_tests_one_fail_middle/expected_results.json
- tests/fail/single_test/expected_results.json
- tests/trunner.nim
This PR renames test files to start with `test_`, rather than end with `_test.nim`, reflecting the same change in the `exercism/nim` repo. See: https://github.com/exercism/nim/commit/573ee59fa9530d1d625bf3c265429fe4c25e3fd3
> Refactor: Rename test files

- Dockerfile
This PR adds compilation/linking flags that make the `runner` binary smaller and faster.
> Build(Dockerfile): Compile with LTO, and strip

- src/runner.nim
- tests/trunner.nim
- tests/trunner_repo_solutions.nim
This PR resolves some deprecation warnings.
Upstream:
- https://github.com/nim-lang/Nim/commit/79c90b30ee55
- https://github.com/nim-lang/Nim/commit/dc5a40f3f39c
- https://github.com/nim-lang/Nim/commit/695154970d83
[CI log before this PR](https://github.com/exercism/nim-test-runner/runs/1336984449#step:6:15): 
```
/opt/test-runner/src/runner.nim(62, 10) Warning: use dirExists; existsDir is deprecated [Deprecated]
/opt/test-runner/src/runner.nim(25, 6) Hint: 'parseCmdLine' is declared but not used [XDeclaredButNotUsed]
/opt/test-runner/tests/trunner.nim(13, 15) template/generic instantiation of `suite` from here
/opt/test-runner/tests/trunner.nim(44, 16) template/generic instantiation of `test` from here
/opt/test-runner/tests/trunner.nim(45, 16) Warning: use fileExists; existsFile is …
```
> Refactor: Prefer `dirExists` and `fileExists`

- .github/workflows/docker.yml
Commit 7f854131a4c2 (#37) added a workflow that pushes images to Amazon
ECR and Docker Hub, but the deployment job also ran on forks. This meant
that a push to the `master` branch of a fork would produce a failing CI
check (see e.g. https://github.com/ee7/nim-test-runner/runs/1663523994)
This commit causes the deployment job to be skipped on forks.
I have pushed this diff to the `master` branch of my fork to show that
this PR works - see https://github.com/ee7/nim-test-runner/runs/1667814901
> CI: Disable the deployment job on forked repos

- .github/workflows/ci.yml
- Dockerfile
- tests/error/compiletime_error_type_mismatch_in_test/expected_results.json
- tests/error/runtime_exception_in_solution/expected_results.json
This commit updates our `Dockerfile` and CI workflow to use the latest
stable Nim release.
This also involves updating some expected error messages so that they
match those produced by Nim 1.4.2 - the only changes are to the
`unittest` line numbers.
Release notes: https://nim-lang.org/blog/2020/12/01/version-142-released.html
In a later PR I'll try to refactor the workflow and Dockerfile so that
we can bump the version number and hash in fewer places.
> Chore: Bump nim from 1.4.0 to 1.4.2

- .github/workflows/ci.yml
- Dockerfile
This commit refactors the CI workflow and the Dockerfile so that each
defines the desired Nim version only once.
For `ci.yml` it does this by changing the testing-only job to install
Nim directly, rather than using a container with the `ubuntu-regular`
image from `nimlang/nim`. This also makes it more obvious that we're
really using the `alpine-slim` image.
Reference docs:
- https://docs.docker.com/engine/reference/builder/#arg
- https://docs.docker.com/engine/reference/builder/#from
> Build: Make it easier to bump the Nim version

- .github/workflows/ci.yml
- .github/workflows/docker.yml
It's unlikely that an automatic Ubuntu update would break things, but we
should pin the major version of GCC along with everything else.
This commit also bumps the Ubuntu version in the CI workflow.
> Build: Pin ubuntu version as 20.04

- .github/dependabot.yml
Commit ea5e8b81b8c9140f6292e39ad86b33962ee2a4b7 (#43) added Dependabot, initially making it bump workflow dependencies `daily` just for testing purposes:
> The workflow dependencies can be bumped less frequently, but let's make
> it `daily` for now just to test.
The bot then showed that it works: it made two PRs that led to https://github.com/exercism/nim-test-runner/commit/4963d832e430a2b1675b38e57f6b5a90b86f56fe and https://github.com/exercism/nim-test-runner/commit/c18c42f5516fc6bccde7b94d0ecf04a5f072683d being merged (although sadly the comments next to the SHA currently have to be updated manually).
This commit reduces the update `interval` for workflow dependencies so that they're only bumped once a month (on the first day of every month).
> Chore(dependabot): Bump actions on a monthly basis

- .github/workflows/ci.yml
- tests/trunner_repo_solutions.nim
In order to test the Nim test runner, we have been running it on every
exercise from the Nim track repo during CI.
However, as part of the preparation for Exercism v3, the v2 exercises on
every track were moved to a new subdirectory: `exercises/practice`. This
caused our CI to indicate failure as the exercises were no longer found.
This commit updates our CI and tests to use the new location for
practice exercises, making CI green again.
See:
- [this failed CI run](https://github.com/exercism/nim-test-runner/pull/48/checks?check_run_id=1846460952)
- https://github.com/exercism/nim/commit/f7ab39d96e32
> CI: Add support for Exercism v3 track structure

- .github/workflows/ci.yml
- tests/trunner_repo_solutions.nim
In order to test the Nim test runner, we have been running it on every
practice exercise from the Nim track repo during CI.
However, for Exercism v3, the example implementation file for each
practice exercise is now supposed in that exercise's `.meta/`
subdirectory, and the Nim track recently moved those files accordingly.
This commit updates our CI and tests so that each `example.nim` file can
be found in its new location, making CI green again.
See https://github.com/exercism/nim/commit/85527fc3d26b
> CI: Update location of `example.nim` files

- src/runner.nim
- tests/error/compiletime_error_closing_quote_expected/expected_results.json
- tests/error/compiletime_error_empty_solution/expected_results.json
- tests/error/compiletime_error_type_mismatch_in_test/expected_results.json
- tests/error/compiletime_error_undeclared_variable_in_solution/expected_results.json
- tests/error/compiletime_exception_in_solution/expected_results.json
- tests/error/runtime_exception_in_solution/expected_results.json
- tests/fail/multiple_tests_all_fail/expected_results.json
- tests/fail/multiple_tests_multiple_fails/expected_results.json
- tests/fail/multiple_tests_multiple_fails_output/expected_results.json
- tests/fail/multiple_tests_one_fail_first/expected_results.json
- tests/fail/multiple_tests_one_fail_last/expected_results.json
- tests/fail/multiple_tests_one_fail_middle/expected_results.json
- tests/fail/single_test/expected_results.json
- tests/fail/single_test_output/expected_results.json
Closes: #14
---
With this PR, the values of our `message` keys are:
```
tests/error/compiletime_crash_in_solution/expected_results.json
3:  "message": "Error: internal error: getTypeDescAux(tyEmpty)\nNo stack traceback available\nTo create a stacktrace, rerun compilation with './koch temp c <file>', see https://nim-lang.github.io/Nim/intern.html#debugging-the-compiler for details\n",
tests/error/compiletime_error_closing_quote_expected/expected_results.json
3:  "message": "hello_world.nim(2, 3) Error: closing \" expected\n",
tests/error/compiletime_error_empty_solution/expected_results.json
3:  "message": "test_identity.nim(9, 7) template/generic instantiation of `suite` from here\ntest_identity.nim(10, 8) template/generic instantiation of `test` from here\ntest_identity.nim(11, 11) …
```
> Fix(runner): Simplify paths in `message` values

- .github/workflows/ci.yml
- src/runner.nim
- src/unittest_json.nim
- tests/error/compiletime_crash_in_solution/expected_results.json
- tests/error/compiletime_error_closing_quote_expected/expected_results.json
- tests/error/compiletime_error_empty_solution/expected_results.json
- tests/error/compiletime_error_type_mismatch_in_test/expected_results.json
- tests/error/compiletime_error_undeclared_variable_in_solution/expected_results.json
- tests/error/compiletime_exception_in_solution/expected_results.json
- tests/error/runtime_exception_in_solution/expected_results.json
- tests/fail/multiple_tests_all_fail/expected_results.json
- tests/fail/multiple_tests_multiple_fails/expected_results.json
- tests/fail/multiple_tests_multiple_fails_output/expected_results.json
- tests/fail/multiple_tests_one_fail_first/expected_results.json
- tests/fail/multiple_tests_one_fail_last/expected_results.json
- tests/fail/multiple_tests_one_fail_middle/expected_results.json
- tests/fail/single_test/expected_results.json
- tests/fail/single_test_output/expected_results.json
- tests/pass/multiple_tests/expected_results.json
- tests/pass/multiple_tests_output/expected_results.json
- tests/pass/multiple_tests_output_truncated/expected_results.json
- tests/pass/multiple_tests_output_unicode_truncated/expected_results.json
- tests/pass/single_test/expected_results.json
- tests/pass/single_test_output/expected_results.json
- tests/pass/single_test_output_stderr_only/expected_results.json
- tests/pass/single_test_output_unicode/expected_results.json
See [the spec](https://github.com/exercism/docs/blob/main/anatomy/track-tooling/test-runners/interface.md#output-format).
Note that we don't yet add the `test_code` property to our `results.json`, so this PR might be a little premature.
> results.json: add `version` property

- src/runner.nim
This commit fixes an oversight from 3a325057b118 (#21) - the doc comment
for this proc should have been updated.
> runner: fix doc comment

- .github/workflows/ci.yml
- Dockerfile
This commit updates our `Dockerfile` and CI workflow to use the latest
stable Nim release.
See the [release blog post](https://nim-lang.org/blog/2021/02/23/versions-144-and-1210-released.html).
Note that due to #40, bumping Nim is easier than before - see #39 for
the previous bump from `1.4.0` to `1.4.2`.
--- 
With this PR, searching git-tracked files for `"1\.4"`:
```
.github/workflows/ci.yml
10:  NIM_VERSION: 1.4.4
Dockerfile
1:ARG NIM_IMAGE=nimlang/nim:1.4.4-alpine-slim@sha256:5c82efe7f3afffe4781f3f127d28c21ecb705dc964cc5434fee98feafd63d2d7
```
> build: bump Nim from 1.4.2 to 1.4.4

- .github/workflows/lint_dockerfile.yml
- Dockerfile
It can be a good idea to lint our Dockerfile. `hadolint` is one such
linter (the name is short for "Haskell Dockerfile Linter") - it
also runs `shellcheck` internally.
Before this commit, running `hadolint` on our Dockerfile would produce:
```
Dockerfile:2 DL3006 warning: Always tag the version of an image explicitly
Dockerfile:7 DL3006 warning: Always tag the version of an image explicitly
Dockerfile:8 DL3018 warning: Pin versions in apk add. Instead of `apk
add <package>` use `apk add <package>=<version>`
```
The first two were false positives, and the third is a real complaint.
Therefore this commit also alters our Dockerfile to workaround the false
positives, and to suppress the warning that is difficult to resolve.
See:
- https://github.com/brpaz/hadolint-action
- …
> ci: add linting of Dockerfile

- .dockerignore
- .github/workflows/shellcheck.yml
- Dockerfile
- bin/install_nim.sh
~I'll tidy up a few more things (e.g. the builder names; symlinking;
maybe use just two build stages instead of three), but I think this PR
is pretty close to complete.~
The resulting Docker image is now smaller than any Nim image I found
in the wild.
I have some ideas to improve it further, but that'll be for a later PR.
The commit message is reproduced below.
---
This commit reduces the size of our Docker image. We were using a
`nimlang/nim` image that is itself based off `alpine:latest`, but we can
just use an `alpine` image directly to avoid some bloat.
```
Before: 249.53 MB
After:  139.68 MB
```
Other advantages:
- Reduced attack surface: we get more control over the image contents -
we can remove things that we don't need in the test runner
environment, like `nodejs`.
- We are no …
> build: use `alpine` directly, not `nimlang/nim`

- .github/workflows/ci.yml
- bin/install_nim.sh
This commit updates our Docker image and CI workflow to use the latest
stable Nim release.
See the [release blog post](https://nim-lang.org/blog/2021/04/15/versions-146-and-1212-released.html).
---
There are two places to bump it at the moment. With this PR:
```
$ git grep --heading --break '1\.4'
.github/workflows/ci.yml
10:  NIM_VERSION: 1.4.6
.github/workflows/docker.yml
23:        uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # 2.1.4
bin/install_nim.sh
6:readonly NIM_VERSION='1.4.6'
```
It's deliberate that the `bin/install_nim.sh` currently doesn't read from an environment variable. But maybe I should've given the two `NIM_VERSION` different names.
> build: bump Nim from 1.4.4 to 1.4.6

- Dockerfile
This commit picks the low-hanging fruit for reducing the image size further.
The majority of the image size comes from `gcc`, but we don't need LTO
support or the D standard library in our image, so we can remove a few large
files.
```
Image size before this commit: 139.66 MB
Image size with this commit:    87.46 MB
```
Note that the alpine package manager doesn't support force-removing package dependencies,
and I don't think there's a split package for a more minimal `gcc` install.
---
```
The largest files in the image, before deleting unneeded files:
156.0K	/usr/bin/strip
160.0K	/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/plugin/include/gimple.h
164.0K	/usr/libexec/gcc/x86_64-alpine-linux-musl/10.2.1/plugin/gengtype
180.0K	/lib/libapk.so.3.12.0
184.0K	/usr/lib/libitm.a
212.0K …
```
> Dockerfile: slim down gcc installation

- .github/workflows/ci.yml
- Dockerfile
- src/runner.nim
I'd like to try `tcc` as our C compiler, at least during the beta
period. It has much faster compile times than `gcc`, which should make
things much more responsive for the user.
It's good for non-optimized builds, which is exactly our use case.
Generally it works well, especially for simple programs like Exercism
solutions. But in the long-term, Nim will only fully support GCC, Clang
and MSVC.
We might want to use `tcc` until Nim gains incremental compilation. The
alternative is to add a pre-built `nimcache` into the image and make the
compiler use that when compiling every user's solution. But I want to
try this first.
In the worst case, we can revert this commit before the release of
Exercism v3.
If we stick with `tcc` we probably want to build it from the
maintained branch, rather …
> build: use `tcc`, not `gcc`

- Dockerfile
Release notes:
https://alpinelinux.org/posts/Alpine-3.14.0-released.html
---
I'm not sure if dependabot is able to bump this.
It looks like the update was pushed to Docker Hub at `2021-06-15T23:23:??+00:00`, but dependabot didn't bump it with this configuration:
https://github.com/exercism/nim-test-runner/blob/eb9c0a468787f0e57b907125fdcb14d071a5cb7d/.github/dependabot.yml#L10-L15
I'll leave alpine unbumped on the main branch of my fork for a while to see if dependabot opens a PR there.
> Dockerfile: bump Alpine from 3.13.5 to 3.14.0

- .github/workflows/lint_dockerfile.yml
`hadolint-action` was originally created by brpaz, but has since been
incorporated into the hadolint organization.
> ci(lint_dockerfile): change `hadolint-action` upstream

- src/unittest_json.nim
Before this commit, compiling `unittest_json` with a development version
of Nim (more recent than 2021-04-26) would produce:
```
Error: undeclared identifier: '<//>'
```
This is because `<//>` was removed from Nim upstream. See https://github.com/nim-lang/Nim/commit/68e522ececdb
> unittest_json: fix error with devel Nim

- Dockerfile
Release notes:
https://alpinelinux.org/posts/Alpine-3.14.2-released.html
> Dockerfile: bump Alpine from 3.14.1 to 3.14.2

- .github/workflows/ci.yml
- tests/trunner.nim
This introduces line based diffing showing the diff (Git default styled) between the pretty printed output of the `results.json` & `expected_results.json` using the [`diff`](https://github.com/mark-summerfield/diff) package
Previous method [(link to workflow run)](https://github.com/exercism/nim-test-runner/runs/4375278814?check_suite_focus=true#step:5:279)
Current Method [(link to line in workflow run)](https://github.com/exercism/nim-test-runner/runs/4375341170?check_suite_focus=true#step:6:289)
There are still the following issue which have to be ironed out:
- MY PR to update the was styling was merged
> CI: diff json mismatches

- Dockerfile
This uses `exercism/nim-docker-base:18a2d8619faf474ee7afc7ae499f111271eb4e12` to copy over the alpine version of nim for the test-runner because it is already built and doesn't have to be rebuilt on every CI test.
The build times are reduced from ~7.5-8.5 minutes to ~2.5-3.5 minutes (still twice as slow as on ubuntu itself)
The reason for the time reduction is that it takes ~5.5-6.5 minutes to compile the nim compiler which is not related to the test runner itself and can be (and is offloaded) to https://github.com/exercims/nim-docker-base. Which only has to compile the nim compiler once for every change to the Dockerfile as it changes rarely and when it does it's mostly due to dependency upgrades.
> Build: use Exercism's base docker image of nim for test-runner

- .github/workflows/ci.yml
- Dockerfile
This applies both to the CI and the built image
> Build: bump nim from 1.6.0 to 1.6.4

- tests/trunner_repo_solutions.nim
The second commit (6ef5d42b93e0bf466e491a96ea5a748ea913538b) is the one that needs to be reviewed. The first commit (eea79e407058f2d33cdffd91bded3144728ff0be) is just there to be able to use the test file that isn't empty that will be added soon (https://github.com/exercism/nim/pull/339). Without this, the CI fails ([see this run](https://github.com/exercism/nim-test-runner/runs/5559905902?check_suite_focus=true)) because the manipulated test file is invalid thus compilation fails.
**EDIT**: Updated description
> CI: add concepts exercises to tests

- .github/workflows/ci.yml
- .github/workflows/lint_dockerfile.yml
- .github/workflows/shellcheck.yml
These comments can be helpful, but dependabot doesn't support them -
they have to be updated manually in dependabot PRs. To remove the burden
of keeping the comments in sync, let's just remove them.
---
With this PR:
```console
$ git grep --break --heading '@' -- .github/workflows
.github/workflows/ci.yml
18:    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
39:      run: "nimble install https://github.com/ynfle/diff@#ae470e7702fd07a6ea850b2a6f2de701130fa048 -y"
49:    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
78:    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
.github/workflows/deploy.yml
14:    uses: exercism/github-actions/.github/workflows/docker-build-push-image.yml@main
.github/workflows/lint_dockerfile.yml
10: …
```
> github(workflows): remove version comments

- Dockerfile
Before this PR:
https://hub.docker.com/layers/nim-docker-base/exercism/nim-docker-base/0ad461c92d478db8678d6b7f0e4bfc7d414902fd/images/sha256-53558d4a62be5c83028e123ad6be259c416ef614b149df1273f8195346d80047
With this PR:
https://hub.docker.com/layers/nim-docker-base/exercism/nim-docker-base/2bd80b871e44a83c2f3c7d65f29c624e88a663da/images/sha256-2c300f96f6f339042d511bfa93ebf8316a9aed9919ed8c2af9fb23ce35788763
> Dockerfile: update `nim-docker-base` hash

- .github/workflows/ci.yml
- .github/workflows/lint_dockerfile.yml
- .github/workflows/shellcheck.yml
See:
- https://github.com/actions/checkout/releases/tag/v3.0.0
- https://github.com/actions/checkout/blob/main/CHANGELOG.md
- https://github.com/actions/checkout/compare/ec3a7ce11313...a12a3943b4bd
---
Stolen from dependabot on my fork.
> build: bump `actions/checkout` from 2.4.0 to 3.0.0

- .github/workflows/lint_dockerfile.yml
See:
- https://github.com/hadolint/hadolint-action/releases/tag/v1.7.0
- https://github.com/hadolint/hadolint-action/releases/tag/v2.0.0
- https://github.com/hadolint/hadolint-action/releases/tag/v2.1.0
- https://github.com/hadolint/hadolint-action/compare/d7b38582334d...f988afea3da5
---
Stolen from dependabot on my fork.
> ci: bump `hadolint/hadolint-action` from 1.6.0 to 2.1.0

- .dockerignore
I think the `tests` directory can be ignore as the Dockerfile doesn't seem to depend on it and CI [copies the tests files into the container](https://github.com/exercism/nim-test-runner/blob/main/.github/workflows/ci.yml#L91).
> .dockerignore: ignore tests directory

- .github/workflows/ci.yml
Whilst investigating https://forum.exercism.org/t/nim-test-runner-bug-after-exercism-submit/10088/5, I found that we don't yet allow for running the CI workflow manually. This PR adds support for that.
> .github: run ci workflow on workflow_dispatch

- .github/dependabot.yml
This PR changes the interval for dependabot updates to monthly.
Right now, the interval is usually set to daily, which results in (almost) daily notifications for Exercism maintainers, and frequent Docker updates to all tooling repos.
To reduce the maintenance burden, we are lowering the frequency to monthly. Due to Exercism's setup, it is unlikely that dependabot issues in our repositories need to be handled with any urgency, so we consider this to be a wise tradeoff.
For maintained track repos, maintainers can choose to close this PR unmerged. But for tooling repos and unmaintained tracks, we are requiring it to be merged.
Thanks!
> .github(dependabot): change Docker interval from daily to monthly
